name: dacodes_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project developed by Arturo.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  crypto: ^3.0.3
  logger: ^1.3.0
  url_launcher: ^6.1.11

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: Spiderman
      fonts:
        - asset: assets/fonts/spiderman_font.ttf
    - family: Comics
      fonts:
        - asset: assets/fonts/comics.ttf
      
